# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hyprfin
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-hwe
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos/repo/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-addons/fedora-%OS_VERSION%/bieszczaders-kernel-cachyos-addons-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
      - hyprpolkitagent
      - cosmic-desktop

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - com.github.wwmm.easyeffects
        - org.gnome.Loupe
        - com.vivaldi.Vivaldi
        - org.inkscape.Inkscape
        - com.stremio.Stremio
        - org.gimp.GIMP
        - com.heroicgameslauncher.hgl
        - md.obsidian.Obsidian
        - com.vysp3r.ProtonPlus
        - com.surfshark.Surfshark
        - com.github.vikdevelop.photopea_app
        - com.obsproject.Studio
        - io.github.milkshiift.GoofCord
        - com.usebottles.bottles
        - io.missioncenter.MissionCenter
        - org.prismlauncher.PrismLauncher
        - io.github.pwr_solaar.solaar
        - net.shadps4.shadPS4
        - org.godotengine.Godot
        - org.libreoffice.LibreOffice
        - io.github.dvlv.boxbuddyrs
      remove:
        - org.gnome.eog

  - type: script
    snippets:
      - "dnf install -y \ https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \ https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"
      - "dnf install -y steam"
      - "dnf install -y dnf-plugins-core"
      - "dnf config-manager -y setopt fedora-cisco-openh264.enabled=1"    
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
